### ISSUE TITLE
How do I convert the following code to cusharp code

### ISSUE THREAD

**Issue by williamlzw** [CuSharp/CuSharp#2]
__global__ void image_crop(float* image_float, cudaTextureObject_t texture_object, int map_y0, int map_x0)
    {
	    int cropped_y = blockIdx.x;
	    int cropped_x = threadIdx.x;
	    int cropped_width = blockDim.x;
    
	    float map_y = float(map_y0 + cropped_y);
	    float map_x = float(map_x0 + cropped_x);
    
	    float map_value = tex2D<float>(texture_object, map_x + 0.5, map_y + 0.5);
	    image_float[cropped_y * cropped_width + cropped_x] = (map_value - 0.5) / 0.225;
    }

**Comment by jason-benz** [comment]
Currently cudaTextureObject_t and tex2D are not supported and not planned for the future. CuSharp supports a subset of the C# functions (and the corresponding C++ equivalent). But you can use a two-dimensional array instead of the texture object.
We just updated the readme and added the language specification. That should help along with the examples.

**Comment by williamlzw** [comment]
Do you have plans to package tensorrt?

**Comment by jason-benz** [comment]
In general, no changes to the CuSharp project are planned for the next few months (except for important bug fixes, in case bugs appear).
